### ISSUE TITLE
Your flow credentials file is encrypted using a system-generated key. - Message received

### ISSUE THREAD

**Issue by shanse01** [sandgatan45/homebridge-node-red#1]
**Describe Your Problem:**
Help is needed on resolving the issue described by your Message:
---------------------------------------------------------------------
Your flow credentials file is encrypted using a system-generated key.

If the system-generated key is lost for any reason, your credentials
file will not be recoverable, you will have to delete it and re-enter
your credentials.

You should set your own key using the 'credentialSecret' option in
your settings file. Node-RED will then re-encrypt your credentials
file using your chosen key the next time you deploy a change.
---------------------------------------------------------------------
**What needs to be done where, please?**
**Logs:**
[11/02/2024, 21:08:16] [NodeRedHomebridgePlugin] Initializing NodeRedHomebridgePlugin platform...
[11/02/2024, 21:08:16] [NodeRedHomebridgePlugin] Finished initializing platform: NodeRedHomebridgePlugin
[11/02/2024, 21:08:16] Loading 5 accessories...
[11/02/2024, 21:08:16] [NodeRedHomebridgePlugin] Flows file existed.```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**
{
    "name": "NodeRedHomebridgePlugin",
    "port": 1957,
    "platform": "NodeRedHomebridgePlugin"
}
```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:** Raspberry PI 5

* **Plugin Version**: 2.1.0
* **Homebridge Version**: 1.7.0 UI 4.55.1
* **Node.js Version**: 20.10.0
* **NPM Version**: 10.2.3
* **Operating System**: Debian GNU/Linux Bookworm (12)

**Comment by helander** [comment]
At the moment I do not think there is anything you could do. However I have planned to support Node-Red settings via the plugin config. I will try to speed up the inclusion of this.

**Comment by helander** [comment]
A new version (v2.2.0) is now available. This version allows you to set arbitrary settings via the plugin’s configuration UI (or via config.json).

**Comment by helander** [comment]
Closing. New version solve problem.

**Comment by helander** [comment]
Close
