### ISSUE TITLE
Node Red - Password protected

### ISSUE THREAD

**Issue by Maverick5269-lab** [sandgatan45/homebridge-node-red#2]
Hi,

It is a really good plug-in for HB.
I think it will be important to have password protected NodeRed.

Can this be implemented using plug-in config?

Thanks in advance

**Comment by helander** [comment]
Hi

Nice to hear that you like the plugin. I have updated the README to include instructions on how to add the setting you asked for. It should be possible to enter the same information via plug-in config UI (basically removing the backslashes, according to the existing documentation). 

Hope this works out for you and please get in touch in case you need further assistance.

**Comment by Maverick5269-lab** [comment]
works perfect thanks!!
